#
###################################
# Site wide configuration
####################################
#
title: NESOY Blog
email: kyoje11@naver.com
description: NESOY Blog
url: https://nesoy.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Kwon Young Jae
  avatar: YoungJae.jpg
  job: "Software developer"
  bio: "Que Sera Sera"
  email: "kyoje11@naver.com"
  disqus-shortname: nesoy
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-89701804-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: nesoy
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
